name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm install
      working-directory: website

    - name: Run tests
      run: npm run test:headless
      working-directory: website     

    - name: Build
      run: npm run build:prod
      working-directory: website

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/website
        enable_jekyll: true
      working-directory: website